base_url           = "https://ccjmne.sh/blog/"
author             = "EÃÅric NICOLAS (ccjmne)"
title              = "ccjmne's blog"
compile_sass       = true
generate_feeds     = true
build_search_index = false
default_language   = "en"
taxonomies         = [{ name = "tags" }, { name = "section" }]

[link_checker]
internal_level = "warn"

[markdown]
github_alerts       = true
bottom_footnotes    = true
insert_anchor_links = "left"

[markdown.highlighting]
light_theme = "catppuccin-latte"
dark_theme  = "catppuccin-frappe"
style       = "class"

[extra]
